### ISSUE TITLE
struggling to get it working

### ISSUE THREAD

**Issue by idkpmiller** [ekt1701/Alexa-Good-Morning#1]
Hi,
If I say 'Alexa, ask Good Morning' in the alexa ASK test service simulator (text) then I see the following Lamda request & response.

# REQUEST:
````
{
  "session": {
    "sessionId": "SessionId.d4ce713b-0875-4a13-a7eb-f46516cd6576",
    "application": {
      "applicationId": "amzn1.ask.skill.1ece9cfa-badd-44e4-8942-8354a7b7831e"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AH3ZFTQUP3EXBAJXJ66UOSXSOEFDAGM7CMIELVVW7KCKBD7IVIUOXNAJAJCMWKIIAJXJQFKBPRL34CL5ROLFFLJVIIWDWPDFJCQRGH6HVL4JSKKBRTJY22INRF4SY4SH3535DYI47WA3VOUSUVJYQ65FUDOTAXTWOGOMRSJIVOB3U7PSSFYC22VO6EHXR7ORRNGNQ3M6GVVJTIY"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.80cffa0f-ca5f-4368-92e1-530bf880657d",
    "locale": "en-US",
    "timestamp": "2017-01-14T01:09:10Z",
    "intent": {
      "name": "getJokeIntent",
      "slots": {}
    }
  },
  "version": "1.0"
}
````

=============
# RESPONSE:
````
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "Here is joke for you: Why do seagulls fly over the sea? Because they aren't bay-gulls! Would you like to hear something else?"
    },
    "reprompt": {
      "outputSpeech": {
        "type": "PlainText",
        "text": "No joy, say again."
      }
    },
    "shouldEndSession": false
  },
  "sessionAttributes": {}
}
````
------------
Now if try asking alexa the same thing she says
"There is a problem with the requested skills response"

I am struggling to troubleshoot this and would welcome some tips

In Lambda the cloudwatch provides this log output.

# LOG:
---------------------------
````
START RequestId: d30b0897-d9f1-11e6-9292-3b4758fc8181 Version: $LATEST
event.session.application.applicationId=amzn1.ask.skill.1ece9cfa-badd-44e4-8942-8354a7b7831e
on_session_started requestId=EdwRequestId.867cbcfa-6195-441e-8b3d-bcea514a4539, sessionId=SessionId.ea00bdf7-e787-448f-bc78-eddebc5b88d9
on_intent requestId=EdwRequestId.867cbcfa-6195-441e-8b3d-bcea514a4539, sessionId=SessionId.ea00bdf7-e787-448f-bc78-eddebc5b88d9
END RequestId: d30b0897-d9f1-11e6-9292-3b4758fc8181
REPORT RequestId: d30b0897-d9f1-11e6-9292-3b4758fc8181	Duration: 514.67 ms	Billed Duration: 600 ms Memory Size: 128 MB	Max Memory Used: 17 MB	
START RequestId: 21240dd4-d9f3-11e6-83cb-7b6469ba0b6a Version: $LATEST
event.session.application.applicationId=amzn1.ask.skill.1ece9cfa-badd-44e4-8942-8354a7b7831e
on_session_started requestId=amzn1.echo-api.request.8cbf7487-796c-4d2f-85f0-02c133880f8d, sessionId=amzn1.echo-api.session.eb8a8c56-cffb-4cb4-a535-8beb2a35625d
on_launch requestId=amzn1.echo-api.request.8cbf7487-796c-4d2f-85f0-02c133880f8d, sessionId=amzn1.echo-api.session.eb8a8c56-cffb-4cb4-a535-8beb2a35625d
'NoneType' object has no attribute '__getitem__': TypeError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 31, in lambda_handler
return on_launch(event['request'], event['session'])
File "/var/task/lambda_function.py", line 53, in on_launch
return get_welcome_response()
File "/var/task/lambda_function.py", line 157, in get_welcome_response
report = reportHeadlineNews()
File "/var/task/lambda_function.py", line 555, in reportHeadlineNews
newsreports = data['responseData']['feed']['entries']
TypeError: 'NoneType' object has no attribute '__getitem__'

END RequestId: 21240dd4-d9f3-11e6-83cb-7b6469ba0b6a
REPORT RequestId: 21240dd4-d9f3-11e6-83cb-7b6469ba0b6a	Duration: 1060.36 ms	Billed Duration: 1100 ms Memory Size: 128 MB	Max Memory Used: 17 MB	
START RequestId: 21d116f7-d9f3-11e6-bf9e-c3d265629327 Version: $LATEST
event.session.application.applicationId=amzn1.ask.skill.1ece9cfa-badd-44e4-8942-8354a7b7831e
on_session_ended requestId=amzn1.echo-api.request.773229ae-1c35-4e75-97aa-bd1a3bd2a249, sessionId=amzn1.echo-api.session.eb8a8c56-cffb-4cb4-a535-8beb2a35625d
END RequestId: 21d116f7-d9f3-11e6-bf9e-c3d265629327
REPORT RequestId: 21d116f7-d9f3-11e6-bf9e-c3d265629327	Duration: 0.20 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 17 MB	
START RequestId: 6397508f-d9f3-11e6-a845-13d21a6d6018 Version: $LATEST
event.session.application.applicationId=amzn1.ask.skill.1ece9cfa-badd-44e4-8942-8354a7b7831e
on_session_started requestId=amzn1.echo-api.request.1f2d8f74-d2a1-44ff-9906-a6d67028b902, sessionId=amzn1.echo-api.session.bc384057-da02-4193-9dba-3d9609154187
on_launch requestId=amzn1.echo-api.request.1f2d8f74-d2a1-44ff-9906-a6d67028b902, sessionId=amzn1.echo-api.session.bc384057-da02-4193-9dba-3d9609154187
'NoneType' object has no attribute '__getitem__': TypeError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 31, in lambda_handler
return on_launch(event['request'], event['session'])
File "/var/task/lambda_function.py", line 53, in on_launch
return get_welcome_response()
File "/var/task/lambda_function.py", line 157, in get_welcome_response
report = reportHeadlineNews()
File "/var/task/lambda_function.py", line 555, in reportHeadlineNews
newsreports = data['responseData']['feed']['entries']
TypeError: 'NoneType' object has no attribute '__getitem__'

END RequestId: 6397508f-d9f3-11e6-a845-13d21a6d6018
REPORT RequestId: 6397508f-d9f3-11e6-a845-13d21a6d6018	Duration: 865.89 ms	Billed Duration: 900 ms Memory Size: 128 MB	Max Memory Used: 17 MB	
START RequestId: 6420a530-d9f3-11e6-b8bb-1f864000be74 Version: $LATEST
event.session.application.applicationId=amzn1.ask.skill.1ece9cfa-badd-44e4-8942-8354a7b7831e
on_session_ended requestId=amzn1.echo-api.request.c00ea468-cc9c-4828-b53a-ba2b4036a655, sessionId=amzn1.echo-api.session.bc384057-da02-4193-9dba-3d9609154187
END RequestId: 6420a530-d9f3-11e6-b8bb-1f864000be74
REPORT RequestId: 6420a530-d9f3-11e6-b8bb-1f864000be74	Duration: 0.42 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 17 MB	
START RequestId: 0e347593-d9f6-11e6-9156-05228f2307c1 Version: $LATEST
event.session.application.applicationId=amzn1.ask.skill.1ece9cfa-badd-44e4-8942-8354a7b7831e
on_session_started requestId=EdwRequestId.80cffa0f-ca5f-4368-92e1-530bf880657d, sessionId=SessionId.d4ce713b-0875-4a13-a7eb-f46516cd6576
on_intent requestId=EdwRequestId.80cffa0f-ca5f-4368-92e1-530bf880657d, sessionId=SessionId.d4ce713b-0875-4a13-a7eb-f46516cd6576
END RequestId: 0e347593-d9f6-11e6-9156-05228f2307c1
REPORT RequestId: 0e347593-d9f6-11e6-9156-05228f2307c1	Duration: 385.71 ms	Billed Duration: 400 ms Memory Size: 128 MB	Max Memory Used: 17 MB	
START RequestId: a0114fa1-d9f6-11e6-8d04-2d850dcd26d1 Version: $LATEST
event.session.application.applicationId=amzn1.ask.skill.1ece9cfa-badd-44e4-8942-8354a7b7831e
on_session_started requestId=amzn1.echo-api.request.03250dd4-d017-4641-8ec0-1dcc9a07d926, sessionId=amzn1.echo-api.session.bcb9f21d-4c10-44c8-9200-a79a9da5dacb
on_launch requestId=amzn1.echo-api.request.03250dd4-d017-4641-8ec0-1dcc9a07d926, sessionId=amzn1.echo-api.session.bcb9f21d-4c10-44c8-9200-a79a9da5dacb
'NoneType' object has no attribute '__getitem__': TypeError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 31, in lambda_handler
return on_launch(event['request'], event['session'])
File "/var/task/lambda_function.py", line 53, in on_launch
return get_welcome_response()
File "/var/task/lambda_function.py", line 157, in get_welcome_response
report = reportHeadlineNews()
File "/var/task/lambda_function.py", line 555, in reportHeadlineNews
newsreports = data['responseData']['feed']['entries']
TypeError: 'NoneType' object has no attribute '__getitem__'

END RequestId: a0114fa1-d9f6-11e6-8d04-2d850dcd26d1
REPORT RequestId: a0114fa1-d9f6-11e6-8d04-2d850dcd26d1	Duration: 885.40 ms	Billed Duration: 900 ms Memory Size: 128 MB	Max Memory Used: 17 MB	
START RequestId: a0a4688a-d9f6-11e6-b473-f92104484d66 Version: $LATEST
event.session.application.applicationId=amzn1.ask.skill.1ece9cfa-badd-44e4-8942-8354a7b7831e
on_session_ended requestId=amzn1.echo-api.request.4de1aadc-5a23-47bc-9f6f-9e18cb41da6f, sessionId=amzn1.echo-api.session.bcb9f21d-4c10-44c8-9200-a79a9da5dacb
END RequestId: a0a4688a-d9f6-11e6-b473-f92104484d66
REPORT RequestId: a0a4688a-d9f6-11e6-b473-f92104484d66	Duration: 0.22 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 17 MB	
````
------------------------------------
I am not sure what to try next, anything stick out?

Thanks

Paul

**Comment by ekt1701** [comment]
Sorry, for the late response, I did not receive any notice about your issue.  The problem was the headline news feed, the api was discontinued.  I was able to fix it.  Please use the latest version of the code.
